name: extinct_games
description: Raise awareness about the biodiversity loss we face each day.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.1.3
  url_launcher: ^5.4.11

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
