import '../../models/animals.dart';

class AnimalProvider {
  final List<Animal> _allAnimals = [
    Animal(
        'Black Rhino',
        'Diceros bicornis',
        'More than 5500',
        'https://extinction-games-assets.s3.amazonaws.com/black-rhino.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/black-rhino.jpg',
        'Population distribution of the Black Rhino (Click for larger view) Black rhinos are the smaller of the two African rhino species. The most notable difference between white and black rhinos are their hooked upper lip. This distinguishes them from the white rhino  which has a square lip. Black rhinos are browsers rather than grazers  and their pointed lip helps them feed on leaves from bushes and trees. They have two horns  and occasionally a third  small posterior horn. Populations of black rhino declined dramatically in the 20th century at the hands of European hunters and settlers. Between 1960 and 1995  black rhino numbers dropped by a sobering 98%  to less than 2 500. Since then  the species has made a tremendous comeback from the brink of extinction. Thanks to persistent conservation efforts across Africa  black rhino numbers have doubled from their historic low 20 years ago to between 5 042 and 5 455 today. However  the black rhino is still considered Critically Endangered endangered  and a lot of work remains to bring the numbers up to even a fraction of what it once was—and to ensure that it stays there. Wildlife crime—in this case  poaching and black-market trafficking of rhino horn—continues to plague the species and threaten its recovery. ',
        'Critically Endangered',
        'Namibia Coastal East Africa Deserts Grasslands'),
    Animal(
        'Cross River Gorilla',
        'Gorilla gorilla diehli',
        '200 to 300 individuals',
        'https://extinction-games-assets.s3.amazonaws.com/cross-river-gorilla.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/cross-river-gorilla.jpg',
        'This subspecies of the western gorilla is very similar in appearance to the more numerous western lowland gorilla  but subtle differences can be found in the skull and tooth dimensions. Cross River gorillas live in a region populated by many humans who have encroached upon the gorilla’s territory—clearing forests for timber and to create fields for agriculture and livestock. Poaching occurs in the forests as well  and the loss of even a few of these gorillas has a detrimental effect on such a small population. Efforts to protect these animals are focused on securing the forests that house them. WWF and partners have worked with the governments of Cameroon and Nigeria to create a protected area for the Cross River gorilla that spans the border of these two nations. ',
        'Critically Endangered',
        'Congo Basin Forest Habitat'),
    Animal(
        'Hawksbill Turtle',
        'Eretmochelys imbricata',
        '',
        'https://extinction-games-assets.s3.amazonaws.com/hawksbill-turtle.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/hawksbill-turtle.jpg',
        'Hawksbills are named for their narrow  pointed beak. They also have a distinctive pattern of overlapping scales on their shells that form a serrated-look on the edges. These colored and patterned shells make them highly-valuable and commonly sold as "tortoiseshell" in markets. Hawksbills are found mainly throughout the world\'s tropical oceans  predominantly in coral reefs. They feed mainly on sponges by using their narrow pointed beaks to extract them from crevices on the reef  but also eat sea anemones and jellyfish. Sea turtles are the living representatives of a group of reptiles that has existed on Earth and travelled our seas for the last 100 million years. They are a fundamental link in marine ecosystems and help maintain the health of coral reefs and sea grass beds. ',
        'Critically Endangered',
        'Mesoamerican Reef Coastal East Africa Coral Triangle'),
    Animal(
        'Orangutan',
        'Pongo abelii',
        'about 104700 (Bornean)  13846 (Sumatran)  800 (Tapanuli)',
        'https://extinction-games-assets.s3.amazonaws.com/orangutan.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/orangutan.jpg',
        'The name orangutan means "man of the forest" in the Malay language. In the lowland forests in which they reside  orangutans live solitary existences. They feast on wild fruits like lychees  mangosteens  and figs  and slurp water from holes in trees. They make nests in trees of vegetation to sleep at night and rest during the day. Adult male orangutans can weigh up to 200 pounds. Flanged males have prominent cheek pads called flanges and a throat sac used to make loud verbalizations called long calls. An unflanged male looks like an adult female. In a biological phenomenon unique among primates  an unflanged male can change to a flanged male for reasons that are not yet fully understood. Bornean and Sumatran orangutans differ a little in appearance and behavior. While both have shaggy reddish fur  Sumatran orangutans have longer facial hair. Sumatran orangutans are reported to have closer social bonds than their Bornean cousins. Bornean orangutans are more likely to descend from the trees to move around on the ground. Both species have experienced sharp population declines. A century ago there were probably more than 230 000 orangutans in total  but the Bornean orangutan is now estimated at about 104 700 based on updated geographic range (Endangered) and the Sumatran about 7 500 (Critically Endangered Endangered). A third species of orangutan was announced in November  2017. With no more than 800 individuals in existence  the Tapanuli orangutan is the most endangered of all great apes. ',
        'Critically Endangered',
        'Forest Habitat'),
    Animal(
        'Sumatran Elephant',
        'Elephas maximus sumatranus',
        '2400 – 2800',
        'https://extinction-games-assets.s3.amazonaws.com/sumatran-elephant.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/sumatran-elephant.jpg',
        'Sumatran elephants feed on a variety of plants and deposit seeds wherever they go  contributing to a healthy forest ecosystem. They also share their lush forest habitat with several other endangered species  such as the Sumatran rhino  tiger  and orangutan  and countless other species that all benefit from an elephant population that thrives in a healthy habitat. ',
        'Critically Endangered',
        'Borneo and Sumatra Forest Habitat'),
    Animal(
        'Sumatran Rhino',
        'Dicerorhinus sumatrensis',
        '80',
        'https://extinction-games-assets.s3.amazonaws.com/sumatran-rhino.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/sumatran-rhino.jpg',
        'Population distribution of the Sumatran Rhino (Click for larger view) Sumatran rhinos are the smallest of the living rhinoceroses and the only Asian rhino with two horns. They are covered with long hair and are more closely related to the extinct woolly rhinos than any of the other rhino species alive today. Calves are born with a dense covering that turns reddish-brown in young adults and becomes sparse  bristly and almost black in older animals. Sumatran rhinos compete with the Javan rhino for the unenviable title of most threatened rhino species. While surviving in possibly greater numbers than the Javan rhino  Sumatran rhinos are more threatened due to habitat loss and fragmentation. The remaining animals survive in small  fragmented non-viable populations  and with limited possibilities to find each other to breed  its population decline continues. Just two captive females have reproduced in the last 15 years. The Sumatran rhino once roamed as far away as the foothills of the Eastern Himalayas in Bhutan and eastern India  through Myanmar  Thailand  possibly to Vietnam and China  and south through the Malay Peninsula. Today  the species only survives on the Indonesian islands of Sumatra and Borneo. Experts believe the third subspecies is probably extinct.   ',
        'Critically Endangered',
        'Borneo and Sumatra Forest Habitat'),
    Animal(
        'Vaquita',
        'Phocoena sinus',
        'About 10 individuals',
        'https://extinction-games-assets.s3.amazonaws.com/vaquita.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/vaquita.jpg',
        'Map data provided by IUCN. Vaquita  the world\'s rarest marine mammal  is on the edge of extinction. The plight of cetaceans—whales  dolphins  and porpoises—as a whole is exemplified by the rapid decline of the vaquita in Mexico  with about 10 individuals remaining. This little porpoise wasn\'t discovered until 1958 and a little over half a century later  we are on the brink of losing them forever. Vaquita are often caught and drowned in gillnets used by illegal fishing operations in marine protected areas within Mexico\'s Gulf of California. The population has dropped drastically in the last few years. The vaquita has a large dark ring around its eyes and dark patches on its lips that form a thin line from the mouth to the pectoral fins. Its top—the dorsal surface—is dark gray  its sides are pale gray  and its underside—the ventral surface—is white with long  light gray markings. Newborn vaquita have darker coloration and a wide gray fringe of color that runs from the head to the flukes  passing through the dorsal and pectoral fins. They are most often found close to shore in the Gulf\'s shallow waters  although they quickly swim away if a boat approaches. ',
        'Critically Endangered',
        'Gulf of California Ocean Habitat'),
    Animal(
        'Yangtze Finless Porpoise',
        'Neophocaena asiaeorientalis ssp. asiaeorientalis',
        '1000-1800',
        'https://extinction-games-assets.s3.amazonaws.com/yangtze-finless-porpoise.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/yangtze-finless-porpoise.jpg',
        'The Yangtze River  the longest river in Asia  used to be one of the only two rivers in the world that was home to two different species of dolphin—the Yangtze finless porpoise and the Baiji dolphin. However  in 2006 the Baiji dolphin was declared functionally extinct. This was the first time in history that an entire species of dolphin had been wiped off the planet because of human activity. Its close cousin  the Yangtze finless porpoise  is known for its mischievous smile and has a level of intelligence comparable to that of a gorilla. ',
        'Critically Endangered',
        'Yangtze Freshwater habitat'),
    Animal(
        'Asian Elephant',
        'Elephas maximus indicus',
        'Fewer than 50000',
        'https://extinction-games-assets.s3.amazonaws.com/asian-elephant.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/asian-elephant.jpg',
        'The Asian elephant is the largest land mammal on the Asian continent. They inhabit dry to wet forest and grassland habitats in 13 range countries spanning South and Southeast Asia. While they have preferred forage plants  Asian elephants have adapted to surviving on resources that vary based on the area. Asian elephants are extremely sociable  forming groups of six to seven related females that are led by the oldest female  the matriarch. Like African elephants  these groups occasionally join others to form larger herds  although these associations are relatively short-lived. In Asia  elephant herd sizes are significantly smaller than those of savannah elephants in Africa. More than two-thirds of an elephant\'s day may be spent feeding on grasses  but it also eats large amounts of tree bark  roots  leaves  and small stems. Cultivated crops such as bananas  rice  and sugarcane are favorite foods. Elephants are always close to a source of fresh water because they need to drink at least once a day. In Asia  humans have had close associations with elephants over many centuries  and elephants have become important cultural icons. According to Hindu mythology  the gods (deva) and the demons (asura) churned the oceans in a search for the elixir of life so that they would become immortal. As they did so  nine jewels surfaced  one of which was the elephant. In Hinduism  the powerful deity honored before all sacred rituals is the elephant-headed Lord Ganesha  who is also called the Remover of Obstacles. ',
        'Endangered',
        'Eastern Himalayas Greater Mekong Forest Habitat'),
    Animal(
        'Blue Whale',
        'Balaenoptera musculus',
        '10000-25000 individuals',
        'https://extinction-games-assets.s3.amazonaws.com/blue-whale.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/blue-whale.jpg',
        'Blue whale at sunset  Mexico. The blue whale is the largest animal on the planet  weighing as much as 200 tons (approximately 33 elephants). The blue whale has a heart the size of a Volkswagen Beetle. Its stomach can hold one ton of krill and it needs to eat about four tons of krill each day. They are the loudest animals on Earth and are even louder than a jet engine. Their calls reach 188 decibels  while a jet reaches 140 decibels. Their low frequency whistle can be heard for hundreds of miles and is probably used to attract other blue whales. ',
        'Endangered',
        'Southern Chile Gulf of California Coral Triangle Ocean Habitat'),
    Animal(
        'Bonobo',
        'Pan paniscus',
        '10000 to 50000',
        'https://extinction-games-assets.s3.amazonaws.com/bonobo.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/bonobo.jpg',
        'Map data provided by IUCN. Bonobos and chimpanzees look very similar and both share 98.7% of their DNA with humans—making the two species our closest living relatives. Bonobos are usually a bit smaller  leaner and darker than chimpanzees. Their society is also different—bonobo groups tend to be more peaceful and are led by females. They also maintain relationships and settle conflicts through sex. However  bonobo life isn’t entirely violence free; if two groups of bonobos come together  they may engage in serious fighting. Wild bonobos can only be found in forests south of the Congo River in the Democratic Republic of Congo (DRC). Sometimes known as the pygmy chimpanzee  bonobos weren’t recognized as a separate species until 1929. As the last great ape to be scientifically described  much remains unknown about the bonobo—including the extent of its geographic range. Efforts to survey the species over the past two decades have been hampered by the remote nature of its habitat  the patchiness of their distribution and years of civil unrest within the DRC. Civil unrest and increasing poverty in the area around the bonobos’ forests have contributed to bonobo poaching and deforestation. Though the size of the bonobo population is largely unknown  it has likely been declining for the last 30 years. Scientists believe that the decline will continue for the next 45 to 55 years due to the bonobo’s low reproductive rate and growing threats.   ',
        'Endangered',
        'Congo Basin Forest Habitat'),
    Animal(
        'Chimpanzee',
        'Pan troglodytes',
        '172700 to 299700',
        'https://extinction-games-assets.s3.amazonaws.com/chimpanzee.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/chimpanzee.jpg',
        'Like us  chimps are highly social animals  care for their offspring for years and can live to be over 50. In fact  chimpanzees are our closest cousins; we share about 98% of our genes. In their habitat in the forests of Central Africa  chimpanzees spend most of their days in the treetops. When they do come down to earth  chimps usually travel on all fours  though they can walk on their legs like humans for as far as a mile. They use sticks to fish termites out of mounds and bunches of leaves to sop up drinking water. ',
        'Endangered',
        'Congo Basin Forest Habitat'),
    Animal(
        'Galápagos Penguin',
        'Spheniscus mendiculus',
        'fewer than 2000',
        'https://extinction-games-assets.s3.amazonaws.com/galapagos-penguin.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/galapagos-penguin.jpg',
        'This is the only penguin species found north of the equator and in the Galápagos.  ',
        'Endangered',
        'The Galápagos'),
    Animal(
        'Green Turtle',
        'Chelonia mydas',
        '',
        'https://extinction-games-assets.s3.amazonaws.com/green-turtle.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/green-turtle.jpg',
        'The green turtle is one of the largest sea turtles and the only herbivore among the different species. Green turtles are in fact named for the greenish color of their cartilage and fat  not their shells. In the Eastern Pacific  a group of green turtles that have darker shells are called black turtles by the local community. Green turtles are found mainly in tropical and subtropical waters. Like other sea turtles  they migrate long distances between feeding grounds and the beaches from where they hatched. Classified as endangered  green turtles are threatened by overharvesting of their eggs  hunting of adults  being caught in fishing gear and loss of nesting beach sites. ',
        'Endangered',
        'Mesoamerican Reef Coastal East Africa Gulf of California The Galápagos Coral Triangle Ocean Habitat'),
    Animal(
        'Humphead Wrasse',
        'Cheilinus undulatus',
        '',
        'https://extinction-games-assets.s3.amazonaws.com/humphead-wrasse.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/humphead-wrasse.jpg',
        'The humphead wrasse is an enormous coral reef fish—growing over six feet long—with a prominent bulge on its forehead. Some of them live to be over 30 years old. They roam through coral reefs in search of hard shelled prey such as mollusks  starfish  or crustaceans. WWF urges local governments in the Coral Triangle to stop the trade and consumption of humphead wrasse—one of the most expensive live reef fishes in the world. Live reef fish trade in Southeast Asia continues to be a significant problem that threatens the region’s food security as well as its reefs  as poachers often resort to legal and destructive fishing methods to catch them. ',
        'Endangered',
        'Coral Triangle Coastal East Africa Ocean Habitat'),
    Animal(
        'Indus River Dolphin',
        'Platanista minor',
        '1816',
        'https://extinction-games-assets.s3.amazonaws.com/indus-river-dolphin.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/indus-river-dolphin.jpg',
        'Indus river dolphins are believed to have originated in the ancient Tethys Sea. When the sea dried up approximately 50 million years ago  the dolphins were forced to adapt to its only remaining habitat—rivers. Today  they can only be found in the lower parts of the Indus River in Pakistan and in River Beas  a tributary of the Indus River in Punjab  India. In Pakistan  their numbers declined dramatically after the construction of an irrigation system  and most dolphins are confined to a 750 mile stretch of the river and divided into isolated populations by six barrages. They have adapted to life in the muddy river and are functionally blind. They rely on echolocation to navigate  communicate and hunt prey including prawns  catfish  and carp. ',
        'Endangered',
        'Freshwater habitat'),
    Animal(
        'Mountain Gorilla',
        'Gorilla beringei beringei',
        'More than 1000',
        'https://extinction-games-assets.s3.amazonaws.com/mountain-gorilla.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/mountain-gorilla.jpg',
        'As their name implies  mountain gorillas live in forests high in the mountains  at elevations of 8 000 to 13 000 feet. They have thicker fur  and more of it  compared to other great apes. The fur helps them to survive in a habitat where temperatures often drop below freezing. But as humans have moved more and more into the gorillas’ territory  the gorillas have been pushed farther up into the mountains for longer periods  forcing them to endure dangerous and sometimes deadly conditions. What might have been a bleak outlook for the subspecies just a couple of decades ago has brightened in recent years due to conservation efforts. Despite ongoing civil conflict  poaching and an encroaching human population  both populations of mountain gorillas have increased in numbers ',
        'Endangered',
        'Congo Basin Forest Habitat Mountains'),
    Animal(
        'Red Panda',
        'Ailurus fulgens',
        'less than 10000 individuals',
        'https://extinction-games-assets.s3.amazonaws.com/red-panda.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/red-panda.jpg',
        'Map data provided by IUCN. The red panda is slightly larger than a domestic cat with a bear-like body and thick russet fur. The belly and limbs are black  and there are white markings on the side of the head and above its small eyes. Red pandas are very skillful and acrobatic animals that predominantly stay in trees. Almost 50% of the red panda’s habitat is in the Eastern Himalayas. They use their long  bushy tails for balance and to cover themselves in winter  presumably for warmth. Primarily an herbivore  the name panda is said to come from the Nepali word ‘ponya ’ which means bamboo or plant eating animal. ',
        'Endangered',
        'Eastern Himalayas Forest Habitat'),
    Animal(
        'Sea Turtle',
        'Cheloniidae and Dermochelyidae families',
        '',
        'https://extinction-games-assets.s3.amazonaws.com/sea-turtle.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/sea-turtle.jpg',
        'Seven different species of sea (or marine) turtles grace our ocean waters  from the shallow seagrass beds of the Indian Ocean  to the colorful reefs of the Coral Triangle and the sandy beaches of the Eastern Pacific. While these highly migratory species periodically come ashore to either bask or nest  sea turtles spend the bulk of their lives in the ocean. WWF\'s work on sea turtles focuses on five of those species: green  hawksbill  loggerhead  leatherback  and olive ridley. Over the last 200 years  human activities have tipped the scales against the survival of these ancient mariners. Slaughtered for their eggs  meat  skin  and shells  sea turtles suffer from poaching and over-exploitation. They also face habitat destruction and accidental capture—known as bycatch—in fishing gear. Climate change has an impact on turtle nesting sites; it alters sand temperatures  which then affects the sex of hatchlings. Nearly all species of sea turtle are now classified as endangered  with three of the seven existing species being Critically Endangered endangered. WWF is committed to stopping the decline of sea turtles and works for the recovery of the species. We work to secure environments in which both turtles and the people that depend upon them can survive. View our sea turtle infographic ',
        'Endangered',
        'Mesoamerican Reef Coastal East Africa Coral Triangle The Galápagos Gulf of California'),
    Animal(
        'Sri Lankan Elephant',
        'Elephas maximus maximus',
        '2500–4000',
        'https://extinction-games-assets.s3.amazonaws.com/sri-lankan-elephant.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/sri-lankan-elephant.jpg',
        'The Sri Lankan subspecies is the largest and also the darkest of the Asian elephants  with patches of depigmentation—areas with no skin color—on its ears  face  The herd size in Sri Lanka ranges from 12-20 individuals or more. It is led by the oldest female  or matriarch. In Sri Lanka  herds have been reported to contain nursing units  consisting of lactating females and their young  and juvenile care units  containing females with juveniles. The Sri Lankan elephant population has fallen almost 65% since the turn of the 19th century. Today  the Sri Lanka elephant is protected under the Sri Lankan law and killing one carries the death penalty. trunk and belly. Once found throughout the tear-shaped island at the bottom of India’s southern tip  these elephants are now being pushed into smaller areas as development activities clear forests and disrupt their ancient migratory routes.',
        'Endangered',
        'Forest Habitat'),
    Animal(
        'Whale',
        'Balaenoptera, Balaena, Eschrichtius, and Eubalaen',
        'Around 400 North Atlantic right whales remain; other species vary: 10000-90000',
        'https://extinction-games-assets.s3.amazonaws.com/whale.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/whale.jpg',
        'Whales roam throughout all of the world\'s oceans  communicating with complex and mysterious sounds. Their sheer size amazes us: the blue whale can reach lengths of more than 100 feet and weigh up to 200 tons—as much as 33 elephants. Despite living in the water  whales breathe air. And like humans  they are warm-blooded mammals who nurse their young. A thick layer of fat called blubber insulates them from cold ocean waters. Some whales are known as baleen whales  including blue  right  bowhead  sei  and gray whales. This refers to the fact that they have special bristle-like structures in their mouths (called baleen) that strain food from the water. Other whales  such as beluga or sperm whales  have teeth. ',
        'Endangered',
        'Southern Chile Arctic The Galápagos Coral Triangle Gulf of California Coastal East Africa Polar Regions'),
    Animal(
        'African Elephant',
        'Loxodonta africana',
        'Approximately 415000 in the wild',
        'https://extinction-games-assets.s3.amazonaws.com/african-elephant.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/african-elephant.jpg',
        'The African elephant is the largest animal walking the Earth. Their herds wander through 37 countries in Africa. They are easily recognized by their trunk that is used for communication and handling objects. And their large ears allow them to radiate excess heat. Upper incisor teeth develop into tusks in African elephants and grow throughout their lifetime. There are two subspecies of African elephants—the Savanna (or bush) elephant and the Forest elephant. Savanna elephants are larger than forest elephants  and their tusks curve outwards. In addition to being smaller  forest elephants are darker and their tusks are straighter and point downward. There are also differences in the size and shape of the skull and skeleton between the two subspecies. Forest elephants  a distinct subspecies of African elephants  are uniquely adapted to the forest habitat of the Congo Basin  but are in sharp decline due to poaching for the international ivory trade. It is estimated that probably one quarter to one third of the total African elephant population is made up of forest elephants. ',
        'Vulnerable',
        'Congo Basin Coastal East Africa Forest Habitat Grasslands'),
    Animal(
        'Black Spider Monkey',
        'Ateles paniscus',
        '',
        'https://extinction-games-assets.s3.amazonaws.com/black-spider-monkey.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/black-spider-monkey.jpg',
        'Map data provided by IUCN. The black spider monkey—also known as the Guiana or red-faced spider monkey—is found in eastern South America in areas north of the Amazon River. They are one of seven species of spider monkeys found in Latin America and one of the largest primate species in South America. ',
        'Vulnerable',
        'Amazon Forest Habitat'),
    Animal(
        'Forest Elephant',
        '',
        '',
        'https://extinction-games-assets.s3.amazonaws.com/forest-elephant.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/forest-elephant.jpg',
        'Forest elephants are an elusive subspecies of African elephants and inhabit the densely wooded rainforests of west and central Africa. Their preference for dense forest habitat prohibits traditional counting methods such as visual identification. Their population is usually estimated through "dung counts"—an analysis on the ground of the density and distribution of the feces. Forest elephants are smaller than savanna elephants  the other African elephant subspecies. Their ears are more oval-shaped ears and their tusks are straighter and point downward (the tusks of savanna elephants curve outwards). There are also differences in the size and shape of the skull and skeleton. Forest elephants are found most commonly in countries with relatively large blocks of dense forest such as Gabon  the Democratic Republic of Congo (DRC)  Cameroon and Central African Republic in central Africa and Côte d’Ivoire  Liberia  and Ghana in west Africa. ',
        'Vulnerable',
        'Congo Basin Namibia Forest Habitat'),
    Animal(
        'Giant Tortoise',
        '',
        '',
        'https://extinction-games-assets.s3.amazonaws.com/giant-tortoise.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/giant-tortoise.jpg',
        'There are many subspecies of giant tortoises that are found on different islands and have different appearances. Those that live on the larger islands where there is more rain have “dome” shaped shells  while those that live in drier conditions are smaller tortoises and have a “saddleback” shell. On June 24  2012  the world-famous giant tortoise affectionately known as “Lonesome George” passed away. He was the last surviving land tortoise from Pinta Island  one of the northern islands in the Galápagos. Thought to be 100 years old  Lonesome George lived at the Charles Darwin Research Station since he was found in 1971. For more than three decades  the Galápagos National Park tried to save the Pinta subspecies by finding George a mate. Unfortunately they did not succeed. Sadly with Lonesome George’s passing  there will be no more Pinta Island tortoises. ',
        'Vulnerable',
        'The Galápagos Ocean Habitat'),
    Animal(
        'Amur Leopard',
        'Panthera pardus orientalis',
        'More than 84 individuals',
        'https://extinction-games-assets.s3.amazonaws.com/amur-leopard.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/amur-leopard.jpg',
        'People usually think of leopards in the savannas of Africa but in the Russian Far East  a rare subspecies has adapted to life in the temperate forests that make up the northern-most part of the species’ range. Similar to other leopards  the Amur leopard can run at speeds of up to 37 miles per hour. This incredible animal has been reported to leap more than 19 feet horizontally and up to 10 feet vertically. The Amur leopard is solitary. Nimble-footed and strong  it carries and hides unfinished kills so that they are not taken by other predators. It has been reported that some males stay with females after mating  and may even help with rearing the young. Several males sometimes follow and fight over a female. They live for 10-15 years  and in captivity up to 20 years. The Amur leopard is also known as the Far East leopard  the Manchurian leopard or the Korean leopard. ',
        'Critically Endangered',
        'Amur-Heilong Forest Habitat Mountains'),
    Animal(
        'Bornean Orangutan',
        'Pongo pygmaeus',
        'About 104700',
        'https://extinction-games-assets.s3.amazonaws.com/bornean-orangutan.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/bornean-orangutan.jpg',
        'Map data provided by IUCN. Bornean orangutan populations have declined by more than 50% over the past 60 years  and the species\' habitat has been reduced by at least 55% over the past 20 years. The Bornean orangutan differs in appearance from the Sumatran orangutan  with a broader face and shorter beard and also slightly darker in color. Three subspecies are recognized  each localized to different parts of the island: ',
        'Critically Endangered',
        'Borneo and Sumatra Forest Habitat'),
    Animal(
        'Eastern Lowland Gorilla',
        'Gorilla beringei graueri',
        'Unknown',
        'https://extinction-games-assets.s3.amazonaws.com/eastern-lowland-gorilla.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/eastern-lowland-gorilla.jpg',
        'Scientists estimate that the population of eastern lowland gorillas has declined by more than 50% since the 1990s when their population numbered 17 000. The eastern lowland gorilla—also known as Grauer’s gorilla—is the largest of the four gorilla subspecies. It is distinguished from other gorillas by its stocky body  large hands and short muzzle. Despite its size  eastern lowland gorillas subsist mainly on fruit and other herbaceous materials  just like other gorilla subspecies. Years of civil unrest in the Democratic Republic of Congo (DRC) have taken their toll on both the eastern lowland gorilla and the mountain gorilla. The eastern lowland gorilla makes its home in lowland tropical rainforests in the eastern DRC. In the last 50 years  its range has decreased from 8 100 square miles—about the size of the state of Massachusetts— to about 4 600 square miles today. This subspecies may now occupy only 13% of its historical range. There were nearly 17 000 eastern lowland gorillas in the mid-1990s but scientists estimate that the population has declined by more than 50% since then. An accurate accounting of the animals has been impossible for many years because of violence in the region. Throughout the unrest  the gorillas have been vulnerable to poaching  even in Kahuzi-Biega National Park  home to the largest population of protected eastern lowland gorillas. Rebels and poachers invaded the park and people set up illegal mines. But  with help from WWF and other organizations  park staff are reestablishing control over the land. ',
        'Critically Endangered',
        'Congo Basin Forest Habitat'),
    Animal(
        'Javan Rhino',
        'Rhinoceros sondaicus',
        '58–68',
        'https://extinction-games-assets.s3.amazonaws.com/javan-rhino.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/javan-rhino.jpg',
        'Population distribution of the Javan Rhino (Click for larger view) Javan rhinos are the most threatened of the five rhino species  with only 58-68 individuals that live only in Ujung Kulon National Park in Java  Indonesia. Javan rhinos once lived throughout northeast India and Southeast Asia. Vietnam’s last Javan rhino was poached in 2010. This species is a dusky grey color and has a single horn of up to about 10 inches. Its skin has a number of loose folds  giving the appearance of armor plating. The Javan rhino is very similar in appearance to the closely-related greater one-horned rhinoceros  but has a much smaller head and less apparent skin folds. ',
        'Critically Endangered',
        'Forest Habitat'),
    Animal(
        'Saola',
        'Pseudoryx nghetinhensis',
        'Unknown',
        'https://extinction-games-assets.s3.amazonaws.com/saola.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/saola.jpg',
        'Map data provided by IUCN. The saola was discovered in May 1992 during a joint survey carried out by the Ministry of Forestry of Vietnam and WWF in north-central Vietnam. The team found a skull with unusual long  straight horns in a hunter\'s home and knew it was something extraordinary. The find proved to be the first large mammal new to science in more than 50 years and one of the most spectacular zoological discoveries of the 20th century. Saola (pronounced: sow-la) are recognized by two parallel horns with sharp ends  which can reach 20 inches in length and are found on both males and females. Meaning “spindle horns” in Vietnamese  they are a cousin of cattle but resemble an antelope. Saola have striking white markings on the face and large maxillary glands on the muzzle  which could be used to mark territory or attract mates. They are found only in the Annamite Mountains of Vietnam and Laos. ',
        'Critically Endangered',
        'Greater Mekong Forest Habitat'),
    Animal(
        'Sumatran Orangutan',
        'Pongo abelii',
        '14 613',
        'https://extinction-games-assets.s3.amazonaws.com/sumatran-orangutan.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/sumatran-orangutan.jpg',
        'Map data provided by IUCN. The Sumatran orangutan is almost exclusively arboreal  living among the trees of tropical rainforests. Females virtually never travel on the ground and adult males do so rarely. Sumatran orangutans are reported to have closer social ties than their Bornean cousins. This has been attributed to mass fruit on fig trees  where groups of Sumatran orangutans can come together to feed. Adult males are typically solitary while females are accompanied by offspring. Historically  the Sumatran orangutan was distributed over the entire island of Sumatra and further south into Java. The species\' range is now restricted to the north of the island with a majority in the provinces of North Sumatra and Aceh. Of the nine existing populations of Sumatran orangutans  only seven have prospects of long-term viability  each with an estimated 250 or more individuals. Only three populations contain more than 1 000 orangutans. Orangutans that were confiscated from the illegal trade or as pets are being reintroduced to Bukit Tigapuluh National Park. They number around 70 and are reproducing.  ',
        'Critically Endangered',
        'Borneo and Sumatra'),
    Animal(
        'Sunda Tiger',
        'Panthera tigris sondaica',
        'Less than 400',
        'https://extinction-games-assets.s3.amazonaws.com/sunda-tiger.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/sunda-tiger.jpg',
        'Sunda tigers are distinguished by heavy black stripes on their orange coats. The last of the Sunda island tigers—estimated to be fewer than 400 today—are holding on for survival in the remaining patches of forest on the island of Sumatra. Accelerating deforestation and rampant poaching mean this noble creature could end up extinct like its Javan and Balinese counterparts. In Indonesia  anyone caught hunting tigers could face jail time and steep fines. But despite increased efforts in tiger conservation—including strengthening law enforcement and antipoaching capacity—a substantial market remains in Sumatra and other parts of Asia for tiger parts and products. Sunda tigers are losing their habitat and prey fast  and poaching is an ever-present threat. ',
        'Critically Endangered',
        'Forest Habitat Grasslands Wetlands'),
    Animal(
        'Western Lowland Gorilla',
        'Gorilla gorilla gorilla',
        'Unknown',
        'https://extinction-games-assets.s3.amazonaws.com/western-lowland-gorilla.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/western-lowland-gorilla.jpg',
        'Map data provided by IUCN. The western lowland gorilla is the most numerous and widespread of all gorilla subspecies. Populations can be found in Cameroon  the Central African Republic  the Democratic Republic of Congo and Equatorial Guinea as well as in large areas in Gabon and the Republic of Congo. The exact number of western lowland gorillas is not known because they inhabit some of the most dense and remote rainforests in Africa. Significant populations still exist  including in isolated swamps and the remote swampy forests of the Republic of Congo. Western lowland gorillas can be distinguished from other gorilla subspecies by their slightly smaller size  their brown-grey coats and auburn chests. They also have wider skulls with more pronounced brow ridges and smaller ears. Large numbers have not protected the western lowland gorilla from decline. Because of poaching and disease  the gorilla’s numbers have declined by more than 60% over the last 20 to 25 years. Even if all of the threats to western lowland gorillas were removed  scientists calculate that the population would require some 75 years to recover. ',
        'Critically Endangered',
        'Congo Basin Forest Habitat'),
    Animal(
        'African Wild Dog',
        'Lycaon pictus',
        '1409',
        'https://extinction-games-assets.s3.amazonaws.com/african-wild-dog.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/african-wild-dog.jpg',
        'Map data provided by IUCN. The wild dog is one of the world’s most endangered mammals. The largest populations remain in southern Africa and the southern part of East Africa (especially Tanzania and northern Mozambique). Wild dogs are social and gather in packs of around ten individuals  but some packs number more than 40. They are opportunistic predators that hunt medium-sized ruminants  such as gazelles. In a sprint  African wild dogs can reach speeds of more than 44 miles per hour. ',
        'Endangered',
        'Coastal East Africa Forest Habitat Grasslands Deserts'),
    Animal(
        'Black-footed Ferret',
        'Mustela nigripes',
        'Approximately 370 in the wild',
        'https://extinction-games-assets.s3.amazonaws.com/black-footed-ferret.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/black-footed-ferret.jpg',
        'Once thought to be globally extinct  black-footed ferrets are making a comeback. For the last thirty years  concerted efforts from many state and federal agencies  zoos  Native American tribes  conservation organizations and private landowners have given black-footed ferrets a second chance for survival. Today  recovery efforts have helped restore the black-footed ferret population to nearly 300 animals across North America. Although great strides have been made to recover the black-footed ferret  habitat loss and disease remain key threats to this highly endangered species. ',
        'Endangered',
        'Northern Great Plains Grasslands'),
    Animal(
        'Bluefin Tuna',
        'Thunnus Thynnus',
        '',
        'https://extinction-games-assets.s3.amazonaws.com/bluefin-tuna.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/bluefin-tuna.jpg',
        'Bluefin are the largest tunas and can live up to 40 years. They migrate across all oceans and can dive deeper than 3 000 feet. Bluefin tuna are made for speed: built like torpedoes  have retractable fins and their eyes are set flush to their body. They are tremendous predators from the moment they hatch  seeking out schools of fish like herring  mackerel  and even eels. They hunt by sight and have the sharpest vision of any bony fish. There are three species of bluefin: Atlantic (the largest and most endangered)  Pacific  and Southern. Most catches of the Atlantic bluefin tuna are taken from the Mediterranean Sea  which is the most important bluefin tuna fishery in the world. ',
        'Endangered',
        'Coral Triangle Ocean Habitat'),
    Animal(
        'Borneo Pygmy Elephant',
        'Elephas maximus borneensis',
        'Approximately 1500',
        'https://extinction-games-assets.s3.amazonaws.com/borneo-pygmy-elephant.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/borneo-pygmy-elephant.jpg',
        'The smallest in size of Asian elephant subspecies  the pygmy elephants of Borneo are baby-faced with oversized ears  plump bellies and tails so long they sometimes drag on the ground as they walk. They are also more gentle-natured than their Asian elephant counterparts. Once believed to be remnants of a domesticated herd given to the Sultan of Sulu in the 17th century  pygmy elephants were determined by WWF to be genetically different from other Asian elephants. DNA evidence proved these elephants were isolated about 300 000 years ago from their cousins on mainland Asia and Sumatra. Over time  they became smaller with relatively larger ears  longer tails and straighter tusks. Today  the pygmy elephants of Borneo are the smallest elephants in Asia. ',
        'Endangered',
        'Borneo and Sumatra'),
    Animal(
        'Fin Whale',
        'Balaenoptera physalus',
        'Between 50000-90000',
        'https://extinction-games-assets.s3.amazonaws.com/fin-whale.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/fin-whale.jpg',
        'Some scientists have speculated that fin whales circle schools of fish with the white side facing the prey and frightening them into denser schools that are easier for the whale to catch. The fin whale  like other baleen whales  strains its food from the water through baleen plates. Next to the blue whale  the fin whale is the second largest mammal in the world. They have a distinct ridge along their back behind the dorsal fin  which gives it the nickname "razorback.” Fin whales have a very unusual feature: the lower right jaw is bright white and the lower left jaw is black.   ',
        'Endangered',
        'Gulf of California Coral Triangle Arctic Ocean Habitat'),
    Animal(
        'Ganges River Dolphin',
        'Platanista gangetica gangetica',
        '1200–1800',
        'https://extinction-games-assets.s3.amazonaws.com/ganges-river-dolphin.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/ganges-river-dolphin.jpg',
        'Dolphins are one of the oldest creatures in the world along with some species of turtles  crocodiles and sharks. The Ganges river dolphin was officially discovered in 1801. Ganges river dolphins once lived in the Ganges-Brahmaputra-Meghna and Karnaphuli-Sangu river systems of Nepal  India  and Bangladesh. But the species is extinct from most of its early distribution ranges. The Ganges river dolphin can only live in freshwater and is essentially blind. They hunt by emitting ultrasonic sounds  which bounces off of fish and other prey  enabling them to “see” an image in their mind. They are frequently found alone or in small groups  and generally a mother and calf travel together. Calves are chocolate brown at birth and then have grey-brown smooth  hairless skin as adults. Females are larger than males and give birth once every two to three years to only one calf. ',
        'Endangered',
        'Eastern Himalayas Freshwater habitat'),
    Animal(
        'Hector\'s Dolphin',
        'Cephalorhynchus hectori',
        'estimated at 7000',
        'https://extinction-games-assets.s3.amazonaws.com/hectors-dolphin.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/hectors-dolphin.jpg',
        'Hector’s dolphins are the smallest and rarest marine dolphins in the world. They have distinct black facial markings  short stocky bodies and a dorsal fin shaped like a Mickey Mouse ear. There is a subspecies of Hector’s dolphin known as Maui’s dolphin that is Critically Endangered endangered and estimated to have a population of only 55. They are found only in the shallow coastal waters along western shores of New Zealand’s North Island. ',
        'Endangered',
        'Ocean Habitat'),
    Animal(
        'Indian Elephant',
        'Elephas maximus indicus',
        '20000 – 25000',
        'https://extinction-games-assets.s3.amazonaws.com/indian-elephant.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/indian-elephant.jpg',
        'Indian elephants may spend up to 19 hours a day feeding and they can produce about 220 pounds of dung per day while wandering over an area that can cover up to 125 square miles. This helps to disperse germinating seeds. They feed mainly on grasses  but large amounts of tree bark  roots  leaves and small stems are also eaten. Cultivated crops such as bananas  rice and sugarcane are favored foods as well. Since they need to drink at least once a day  these elephants are always close to a source of fresh water. ',
        'Endangered',
        'Grasslands'),
    Animal(
        'Irrawaddy Dolphin',
        'Orcaella brevirostris',
        '',
        'https://extinction-games-assets.s3.amazonaws.com/irrawaddy-dolphin.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/irrawaddy-dolphin.jpg',
        'Map data provided by IUCN. Irrawaddy dolphins are found in coastal areas in South and Southeast Asia  and in three rivers: the Ayeyarwady (Myanmar)  the Mahakam (Indonesian Borneo) and the Mekong. The Mekong River Irrawaddy dolphins inhabit a 118-mile stretch of the river between Cambodia and Lao PDR and are scarce—just 92 individuals are estimated to still exist. These dolphins have a bulging forehead  short beak  and 12-19 teeth on each side of both jaws. ',
        'Endangered',
        'Greater Mekong Freshwater habitat'),
    Animal(
        'North Atlantic Right Whale',
        'Eubalaena glacialis',
        '300-350 individuals',
        'https://extinction-games-assets.s3.amazonaws.com/north-atlantic-right-whale.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/north-atlantic-right-whale.jpg',
        'Map data provided by IUCN. The North Atlantic right whale can easily be identified by the white calluses on its head  which are very noticeable against the whale’s dark gray body. It has a broad back without a dorsal fin and a long arching mouth that begins above the eye. A baleen whale  it feeds by swimming through a swarm of plankton with its mouth open and the head slightly above the surface. Right whales are found more often in coastal waters  especially during the breeding season. ',
        'Endangered',
        'Ocean Habitat'),
    Animal(
        'Sea Lions',
        'Zalophus wollebaeki',
        '',
        'https://extinction-games-assets.s3.amazonaws.com/sea-lions.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/sea-lions.jpg',
        'Sea lions haul out in large colonies on rocks and sandy shores on the Islands. They move into the water to feed and cool off as needed. ',
        'Endangered',
        'The Galápagos Ocean Habitat'),
    Animal(
        'Sei Whale',
        'Balaenoptera borealis',
        '',
        'https://extinction-games-assets.s3.amazonaws.com/sei-whale.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/sei-whale.jpg',
        'The sei whale is one of the fastest whales  reaching speeds of up to 30 miles per hour. Sei whales inhabit all oceans and adjoining seas except in tropical and polar regions. Like other great whales  they prefer to spend the summer feeding in cooler waters before migrating to warmer waters to breed and give birth to their calves. ',
        'Endangered',
        'Southern Chile Arctic The Galápagos Coral Triangle Gulf of California Coastal East Africa Ocean Habitat'),
    Animal(
        'Tiger',
        'Panthera tigris',
        'Around 3900',
        'https://extinction-games-assets.s3.amazonaws.com/tiger.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/tiger.jpg',
        'Map data provided by IUCN There are two recognized subspecies of tiger*: the continental (Panthera tigris tigris) and the Sunda (Panthera tigris sondaica). The largest of all the Asian big cats  tigers rely primarily on sight and sound rather than smell for hunting. They typically hunt alone and stalk prey. A tiger can consume more than 80 pounds of meat at one time. On average  tigers give birth to two to four cubs every two years. If all the cubs in one litter die  a second litter may be produced within five months. Tigers generally gain independence at around two years of age and attain sexual maturity at age three or four for females and four or five years for males. Juvenile mortality is high  however—about half of all cubs do not survive more than two years. Tigers have been known to reach up to 20 years of age in the wild. Males of the larger subspecies  the continental tiger  may weigh up to 660 pounds. For males of the smaller subspecies—the Sunda tiger—the upper range is at around 310 pounds. Within both subspecies  males are heavier than females. Tigers are mostly solitary  apart from associations between mother and offspring. Individual tigers have a large territory  and the size is determined mostly by the availability of prey. Individuals mark their domain with urine  feces  rakes  scrapes  and vocalizing. Across their range  tigers face unrelenting pressures from poaching  retaliatory killings  and habitat loss. They are forced to compete for space with dense and often growing human populations.',
        'Endangered',
        'Forest Habitat'),
    Animal(
        'Whale Shark',
        'Rhincodon typus',
        '',
        'https://extinction-games-assets.s3.amazonaws.com/whale-shark.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/whale-shark.jpg',
        'Like human fingerprints  whale sharks have a unique pattern of spots which allow individual sharks to be identified. By taking photos and cataloguing them  WWF has identified 458 different whale sharks in the Philippines. Whale sharks (Rhincodon typus) are the largest shark  and indeed largest of any fishes alive today. They feed on plankton and travel large distances to find enough food to sustain their huge size  and to reproduce. Whale sharks are found in all the tropical oceans of the world. Their white spotted colouration makes these gentle giants easy to distinguish  and popular with snorkelers and divers at sites where they aggregate off the coast. The maximum size of whale sharks is not known  but could be as large as 20m. Females give birth to live young but this has never been observed. Where pupping occurs and where the youngest animals situate remains a mystery  as they are very rarely found. Adults are often found feeding at the surface  but may dive to 1000m. Whale sharks are protected from fishing in many countries these days  but are in decline in some areas.',
        'Endangered',
        'Mesoamerican Reef Coastal East Africa Gulf of California Coral Triangle'),
    Animal(
        'Great White Shark',
        'Carcharodon carcharias',
        '',
        'https://extinction-games-assets.s3.amazonaws.com/white-shark.jpg',
        'https://extinction-games-assets.s3.amazonaws.com/thumbs/white-shark.jpg',
        "The great white shark is the world's largest known predatory fish. It has 300 teeth, yet does not chew its food. Sharks rip their prey into mouth-sized pieces which are swallowed whole. The shark’s heavy, torpedo-shaped body allows it to cruise efficiently for long periods of time, and then suddenly switch to high speed bursts in pursuit of prey—sometimes leaping out of the water. It feeds on a broad spectrum of prey, from small fish, such as halibut, to large seals and dolphins.",
        'Vulnerable',
        'Gulf of California, Southern Chile, The Galápagos, Coastal East Africa'),
  ];

  List<Animal> get animals {
    return _allAnimals;
  }

  Animal getAnimal(int index) {
    return _allAnimals[index];
  }
}
